backend:
  name: git-gateway
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "menu"
    label: "Menu Items"
    folder: "content/menu"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Image", name: "image", widget: "image" }

  - name: "reviews"
    label: "Customer Reviews"
    folder: "content/reviews"
    create: true
    slug: "{{fields.name}}-{{year}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Rating", name: "rating", widget: "number", min: 1, max: 5 }
      - { label: "Message", name: "message", widget: "text" }

  - name: "about"
    label: "About Section"
    files:
      - file: "content/about.md"
        label: "About Us"
        name: "about"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
