backend:
  name: github
  repo: Haarshhit/panditan-di-hatti
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "menu"
    label: "Menu Items"
    folder: "content/menu"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "price", label: "Price", widget: "string" }
      - { name: "image", label: "Image", widget: "image" }
      - { name: "description", label: "Description", widget: "text" }

  - name: "reviews"
    label: "Customer Reviews"
    folder: "content/reviews"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "name", label: "Customer Name", widget: "string" }
      - { name: "review", label: "Review", widget: "text" }
      - { name: "rating", label: "Rating (1-5)", widget: "number", min: 1, max: 5 }
