---
title: "Panditan Di Hatti"
tagline: "Where tradition meets taste – Since 1980 in ANU (Hamirpur)"
description: "Official website of Panditan Di Hatti – famous for Besan Barfi and more."
modi_video: "https://youtu.be/QOZa-VSTyek?si=UAj5cmo9g4x3ipdn"
offers: "🎉 Diwali Offer: 15% off on all sweets!"
footer: "© 2025 Panditan Di Hatti | Website designed by Harshit | Licensed under MIT"
timings: |
  Sunday: 08:00 AM – 08:30 PM
  Monday: 08:00 AM – 08:30 PM
  Tuesday: 08:00 AM – 08:30 PM
  Wednesday: 08:00 AM – 08:30 PM
  Thursday: 08:00 AM – 08:30 PM
  Friday: 08:00 AM – 08:30 PM
  Saturday: 08:00 AM – 08:30 PM
banner_img: /images/LOGO.png
owner_img: /images/OWNER.png
shop_img: /images/SHOP.avif
---
