backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "menu"
    label: "Menu Items"
    folder: "content/menu"
    create: true
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Price", name: "price", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Description", name: "description", widget: "text" }

  - name: "reviews"
    label: "Customer Reviews"
    folder: "content/reviews"
    create: true
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Review", name: "review", widget: "text" }
