backend:
  name: git-gateway
  branch: main

media_folder: "images" # Folder where uploaded files go
public_folder: "/images" # Folder where files will be served from

collections:
  - name: "content" # Used in routes, e.g., /admin/collections/blog
    label: "Content" # Used in the UI
    folder: "content" # The path to the folder where the files are stored
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Banner Text", name: "banner_text", widget: "string" }
      - { label: "Tagline", name: "tagline", widget: "string" }
      - { label: "About Us Text", name: "about_text", widget: "text" }
      - { label: "Owner Image", name: "owner_image", widget: "image" }
      - { label: "Specialties", name: "specialties", widget: "list", fields: [
          { label: "Name", name: "name", widget: "string" },
          { label: "Description", name: "description", widget: "text" },
          { label: "Image", name: "image", widget: "image" }
        ] }
      - { label: "Opening Hours", name: "opening_hours", widget: "list", fields: [
          { label: "Day", name: "day", widget: "string" },
          { label: "Hours", name: "hours", widget: "string" }
        ] }
      - { label: "Customer Reviews", name: "reviews", widget: "list", fields: [
          { label: "Reviewer Name", name: "reviewer_name", widget: "string" },
          { label: "Review", name: "review", widget: "text" }
        ] }
