backend:
  name: auth0
  domain: pandit-di-hatti.us.auth0.com
  client_id: 9T1YDhGiPSGE1XqQmkPHei7IzyFeReN2
  login: true

media_folder: "images/uploads"
public_folder: "/images/uploads"

media_library:
  name: uploadcare
  config: {}

collections:
  - name: "menu"
    label: "Menu Items"
    folder: "content/menu"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Item Name", name: "title", widget: "string" }
      - { label: "Price (₹)", name: "price", widget: "number" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Image", name: "image", widget: "image" }

  - name: "reviews"
    label: "Customer Reviews"
    folder: "content/reviews"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Rating (1–5)", name: "rating", widget: "number", min: 1, max: 5 }
      - { label: "Review", name: "body", widget: "text" }

  - name: "banner"
    label: "Homepage Banner"
    files:
      - label: "Hero Section"
        name: "hero"
        file: "content/hero.md"
        fields:
          - { label: "Heading", name: "heading", widget: "string" }
          - { label: "Subheading", name: "subheading", widget: "text" }
          - { label: "Banner Image", name: "image", widget: "image" }
